# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McqPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperName', models.CharField(max_length=1000)),
                ('createdBy', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='McqQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperId', models.IntegerField()),
                ('question', models.CharField(max_length=1000)),
                ('answerOne', models.CharField(max_length=1000)),
                ('answerTwo', models.CharField(max_length=1000)),
                ('answerThree', models.CharField(max_length=1000)),
                ('answerFour', models.CharField(max_length=1000)),
                ('correctAnswer', models.CharField(max_length=1000)),
            ],
        ),
    ]
